rm -f code/frontend/GymAtHomeFrontend/out/artifacts/GymAtHomeFrontend_war_exploded.war/WEB-INF/classes/clientservlets/ClientPlanServlet.class
rm -f code/frontend/GymAtHomeFrontend/out/artifacts/GymAtHomeFrontend_war_exploded.war/WEB-INF/classes/clientservlets/ClientRegisterServlet.class
rm -f code/frontend/GymAtHomeFrontend/out/artifacts/GymAtHomeFrontend_war_exploded.war/WEB-INF/classes/clientservlets/ClientWorkoutServlet.class
rm -f code/frontend/GymAtHomeFrontend/out/artifacts/GymAtHomeFrontend_war_exploded.war/WEB-INF/classes/clientservlets/MakeRequestServlet.class
rm -f code/frontend/GymAtHomeFrontend/out/artifacts/GymAtHomeFrontend_war_exploded.war/WEB-INF/classes/clientservlets/MyProfileClientServlet.class
rm -f code/frontend/GymAtHomeFrontend/out/artifacts/GymAtHomeFrontend_war_exploded.war/WEB-INF/classes/clientservlets/MyRequestsClientServlet.class
rm -f code/frontend/GymAtHomeFrontend/out/artifacts/GymAtHomeFrontend_war_exploded.war/WEB-INF/classes/clientservlets/PersonalTrainerProfileServlet.class
rm -f code/frontend/GymAtHomeFrontend/out/artifacts/GymAtHomeFrontend_war_exploded.war/WEB-INF/classes/clientservlets/SearchPersonalTrainersServlet.class
rm -f code/frontend/GymAtHomeFrontend/out/artifacts/GymAtHomeFrontend_war_exploded.war/WEB-INF/classes/commonservlets/LoginServlet.class
rm -f code/frontend/GymAtHomeFrontend/out/artifacts/GymAtHomeFrontend_war_exploded.war/WEB-INF/classes/commonservlets/NotificationServlet.class
rm -f code/frontend/GymAtHomeFrontend/out/artifacts/GymAtHomeFrontend_war_exploded.war/WEB-INF/classes/personaltrainerservlets/ClientPlanByPTServlet.class
rm -f code/frontend/GymAtHomeFrontend/out/artifacts/GymAtHomeFrontend_war_exploded.war/WEB-INF/classes/personaltrainerservlets/ClientProfileServlet.class
rm -f code/frontend/GymAtHomeFrontend/out/artifacts/GymAtHomeFrontend_war_exploded.war/WEB-INF/classes/personaltrainerservlets/ClientWorkoutByPTServlet.class
rm -f code/frontend/GymAtHomeFrontend/out/artifacts/GymAtHomeFrontend_war_exploded.war/WEB-INF/classes/personaltrainerservlets/CreateWeekServlet.class
rm -f code/frontend/GymAtHomeFrontend/out/artifacts/GymAtHomeFrontend_war_exploded.war/WEB-INF/classes/personaltrainerservlets/MyClientsServlet.class
rm -f code/frontend/GymAtHomeFrontend/out/artifacts/GymAtHomeFrontend_war_exploded.war/WEB-INF/classes/personaltrainerservlets/MyProfilePersonalTrainerServlet.class
rm -f code/frontend/GymAtHomeFrontend/out/artifacts/GymAtHomeFrontend_war_exploded.war/WEB-INF/classes/personaltrainerservlets/MyRequestsPTServlet.class
rm -f code/frontend/GymAtHomeFrontend/out/artifacts/GymAtHomeFrontend_war_exploded.war/WEB-INF/classes/personaltrainerservlets/PersonalTrainerRegisterServlet.class
rm -f code/frontend/GymAtHomeFrontend/out/artifacts/GymAtHomeFrontend_war_exploded.war/WEB-INF/classes/utils/Utils.class
rm -f code/frontend/GymAtHomeFrontend/out/production/GymAtHomeFrontend/clientservlets/ClientPlanServlet.class
rm -f code/frontend/GymAtHomeFrontend/out/production/GymAtHomeFrontend/clientservlets/ClientRegisterServlet.class
rm -f code/frontend/GymAtHomeFrontend/out/production/GymAtHomeFrontend/clientservlets/ClientWorkoutServlet.class
rm -f code/frontend/GymAtHomeFrontend/out/production/GymAtHomeFrontend/clientservlets/MakeRequestServlet.class
rm -f code/frontend/GymAtHomeFrontend/out/production/GymAtHomeFrontend/clientservlets/MyProfileClientServlet.class
rm -f code/frontend/GymAtHomeFrontend/out/production/GymAtHomeFrontend/clientservlets/MyRequestsClientServlet.class
rm -f code/frontend/GymAtHomeFrontend/out/production/GymAtHomeFrontend/clientservlets/PersonalTrainerProfileServlet.class
rm -f code/frontend/GymAtHomeFrontend/out/production/GymAtHomeFrontend/clientservlets/SearchPersonalTrainersServlet.class
rm -f code/frontend/GymAtHomeFrontend/out/production/GymAtHomeFrontend/commonservlets/LoginServlet.class
rm -f code/frontend/GymAtHomeFrontend/out/production/GymAtHomeFrontend/commonservlets/NotificationServlet.class
rm -f code/frontend/GymAtHomeFrontend/out/production/GymAtHomeFrontend/personaltrainerservlets/ClientPlanByPTServlet.class