version: '3'

#lista de serviços
services:
  mysql_core:
    image: mysql:latest
    environment: 
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=core
    ports:
      - 3306:3306
      - 33060:33060

  core:
    build: ./
    ports:
      - 8080:8080
      - 9990:9990
    links: 
      - mysql_core