FROM jboss/wildfly:12.0.0.Final

COPY Clients.war /opt/jboss/wildfly/standalone/deployments/
COPY Core.war /opt/jboss/wildfly/standalone/deployments/
COPY GymAtHome.war /opt/jboss/wildfly/standalone/deployments/
# COPY Notification.war /opt/jboss/wildfly/standalone/deployments/
COPY PersonalTrainer.war /opt/jboss/wildfly/standalone/deployments/
COPY Request.war /opt/jboss/wildfly/standalone/deployments/
